DROP DATABASE yazTD;
CREATE DATABASE yazTD;
use yazTD;

CREATE TABLE `tw_Accounts` (
    `UserID` INT NOT NULL AUTO_INCREMENT,
    `Username` TEXT NOT NULL,
    `Password` TEXT NOT NULL,
    PRIMARY KEY (`UserID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=COMPACT;